#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


echo '😒😒😒😒wait a minute, we format your code 😒😒😒😒'

yarn prettier-write

yarn check-format ||
(
    echo '🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮'
    false;
)
# Check tsconfig standards
yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check.Are you seriously trying to write that? Make the changes required above.🤡😂❌🤡'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'